### ISSUE TITLE
Licensing question

### ISSUE THREAD

**Issue by hopptimusPrime** [dkelosky/vscode-ibm-jcl#1]
Hi Dan,

Awesome work! As a fellow mainframer, its difficult to find many opensource free-to-use tools that help with mainframe code. (though with Zowe, and other stuff that is changing that!!) although one question / issue preventing me from using it: Would you be able or willing to add a license to these plugins to show that they are open source? similar to how Zowe is under Creative Commons, or other projects are under GNU or MIT, etc. Certain shops look for this in writing.  

I entirely understand if you don't want to. After all:  your code, your choice! Either ways its great to see the platform moving towards a more open direction, and the ability to have HLASM and JCL syntax checking in a modern non-ISPF interface is awesome!! Feel free to close this issue (other than creating an issue, not sure how to reach out to you). 

Thanks for your attention and Best Regards!

**Comment by dkelosky** [comment]
Hi, no problem. It's MIT, and I'll try to add a license file this evening to this and HLASM highlighters. 

I also contribute to Zowe so perhaps I'll try to get this forked there as time permits.

I'll close this when published with MIT.

Take care

**Comment by hopptimusPrime** [comment]
Very awesome! I see the license now! thank you for the quick response! Thank you for all of your hard work!
