### ISSUE TITLE
Too many words detected as inline comments

### ISSUE THREAD

**Issue by ghost** [dkelosky/vscode-ibm-jcl#10]
The text underlined in blue is correctly colored as a comment, but the text underlined in red should not be.
![image](https://user-images.githubusercontent.com/50887074/79343064-ef020700-7efb-11ea-8fd6-96bfb4aca852.png)

The issue seems to be with this regex:
https://github.com/dkelosky/vscode-ibm-jcl/blob/fb57727d92d3162eea7f0e248896cc8930c3e976/syntaxes/jcl.tmLanguage.json#L238

Not sure if there's an easy way to distinguish between spaces that are or aren't followed by comments. This regex seems to work:
`(\\S*)(\\s\\s.*)?`

It's not an ideal solution because it requires at least 2 spaces before a comment, whereas JCL syntax  only requires 1 space, but I think it would cover most cases.

**Comment by dkelosky** [comment]
![image](https://user-images.githubusercontent.com/14940561/82720284-1b8a0b00-9c80-11ea-9091-0ed695067d46.png)

Fixed in `0.7.0`
