### ISSUE TITLE
Too many words detected as keywords

### ISSUE THREAD

**Issue by ghost** [dkelosky/vscode-ibm-jcl#11]
In the JCL below, the text `STEP1.RC` and `STEP1.RUN` shouldn't be highlighted.
![image](https://user-images.githubusercontent.com/50887074/79353224-c6ccd500-7f08-11ea-8b4e-fbadf0b12859.png)

Stricter regular expressions are needed in the Textmate grammar for magenta and blue highlighting.

**Comment by dkelosky** [comment]
Sorry for not responding to this or the other issues.  I'm slowing starting a refactor to change over to yaml (for better maintainability).  I"ll try to get this and other open issues in the meantime.

**Comment by dkelosky** [comment]
![image](https://user-images.githubusercontent.com/14940561/82720300-44aa9b80-9c80-11ea-9d46-46f631bd4dd7.png)

This will not detect sequence numbers (via highlighting) on the `THEN` line.  Published in `0.7.0`
