### ISSUE TITLE
Highlighting of DD parameters continued on next line

### ISSUE THREAD

**Issue by ghost** [dkelosky/vscode-ibm-jcl#17]
For the last 2 JCL statements, I believe their second lines should be purple rather than blue:
![image](https://user-images.githubusercontent.com/50887074/82914969-2671c380-9f3e-11ea-8780-401a33dd44b7.png)
[JCL source](https://www.ibm.com/support/knowledgecenter/zosbasics/com.ibm.zos.zdatamgmt/zsysprogc_utilities_IEBCOPY.htm)

**Comment by dkelosky** [comment]
In new version this will be:
![image](https://user-images.githubusercontent.com/14940561/83083143-5c549c00-a053-11ea-88ed-d47fe9be66d3.png)
