### ISSUE TITLE
Spaces in parameters result in spurious inline comments

### ISSUE THREAD

**Issue by ghost** [dkelosky/vscode-ibm-jcl#18]
This is similar to #10, but happens in a different context.

![image](https://user-images.githubusercontent.com/50887074/82915791-350caa80-9f3f-11ea-9897-e9d74e47ad1c.png)
[JCL source](https://gist.github.com/plavjanik/fbf4fbf4318a1b7a44ac0381a1a39717) - The `/*` is missing and must be added to reproduce the issue

**Comment by dkelosky** [comment]
In new version this will be:
![image](https://user-images.githubusercontent.com/14940561/83083087-30391b00-a053-11ea-9af2-6274f5275a65.png)
