### ISSUE TITLE
In-stream data set highlighting doesn't end with next '//' JCL statement

### ISSUE THREAD

**Issue by mheuzey** [dkelosky/vscode-ibm-jcl#24]
Currently, the highlighting for an in-stream data set only ends when it finds the delimeter '/*'. However, it should also end when the next JCL statement occurs (if the delimeter was omitted).

![image](https://user-images.githubusercontent.com/32349430/83776029-ae9a4c00-a655-11ea-9b99-91eb6c501dac.png)

**Comment by dkelosky** [comment]
Thanks for reporting, will try to knock this out soon
