### ISSUE TITLE
Display in-stream DD data (e.g. the data below SYSIN DD *) as unique color

### ISSUE THREAD

**Issue by ChrisBoehmCA** [dkelosky/vscode-ibm-jcl#4]
In my opinion, it would be cool to display the contents of inline DDs with a unique color to make the statements / data within stand out.

**Comment by ghost** [comment]
A unique color for inline DDs would be nice, currently the highlighting inside an inline DD varies depending on indent level:
![image](https://user-images.githubusercontent.com/50887074/79342676-6daa7480-7efb-11ea-8163-a847dfe025fe.png)

**Comment by dkelosky** [comment]
Hopefully this is better in `0.7.0`:
![image](https://user-images.githubusercontent.com/14940561/82720274-f6959800-9c7f-11ea-8c79-dffb95d8a6f8.png)

It seems to have an issue with sequence numbers on the `DD *` line, but otherwise is an improvement.
