### ISSUE TITLE
Support comment/uncomment functionality in VS Code

### ISSUE THREAD

**Issue by ChrisBoehmCA** [dkelosky/vscode-ibm-jcl#5]
Would be really neat to be able to hit Ctrl + /  and comment a block of JCL. Would probably need language server stuff to be able to do this though, right? Loving the extension

**Comment by dkelosky** [comment]
Please let me know if fixed in the latest publish, 0.4.0

**Comment by ChrisBoehmCA** [comment]
Thanks. It is working. It would be cool for there still to be a few enhancements on this if possible. For instance if I comment lines beginning with "//" it would be cool to just replace that in place with "//*". Know what I mean? But that could be a separate issue if you'd like. Thanks for fixing

**Comment by dkelosky** [comment]
Yeah, that's a good point, might be some troubles in doing that but that's how your would typically comment by hand so it makes sense

**Comment by dkelosky** [comment]
Let's do a separate issue 😁

**Comment by dkelosky** [comment]
I'm going to close this one :)
